{% set name = "pre-commit-uv" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pre_commit_uv-{{ version }}.tar.gz
  sha256: a67f320aa2479cebf1294defc1682a4b37b7d010fa2cf773b58036d6474dee1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
  run:
    - python >={{ python_min }}
    - pre-commit >=3.8
    - python-uv >=0.4.7

test:
  imports:
    - pre_commit_uv
  requires:
    - python {{ python_min }}
  commands:
    - uv pip check

about:
  home: https://github.com/tox-dev/pre-commit-uv
  summary: Run pre-commit with uv
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - anjos
